### ISSUE TITLE
Locking jobs may have a timing issue?

### ISSUE THREAD

**Issue by ferrouswheel** [ideegeo/Daemonise#13]
Noticed that my local VM jobs would sometimes say:

`lock=activejob:8bXXXXXXXXXXXXfa cannot acquire lock hold by WORKERNAME:PID`

This would happen after WORKERNAME logs:
```
sent message to NEXTWORKER
acknowledging AMQP message
```

and NEXTWORKER logs:
```
received message body: ...
lock=activejob:8bXXXXXXXXXXXXfa cannot acquire lock hold by WORKERNAME:PID
```

It seems that NEXTWORKER might receive the message before the previous one has unlocked it.

It's also currently unclear to me whether a job being locked does anything except report when the job is locked and set the daemonise `job_locked` variable. Is it up to the individual workers to decide what to do if the job can't be locked?

**Comment by ferrouswheel** [comment]
Looks like this was something dying unexpectedly. Would still be keen to here about how job_locked is designed to be used though :-)

**Comment by nupfel** [comment]
ping me next time in the office about it! in general the worker will not continue doing anything with three job if it couldn't lock it leading to the job eventually dying unless there is actuary another active worker on it still which should be the norm.
but the job is definitely unlocked just before the message is sent off.
