### ISSUE TITLE
KyotoTycoon plugin silently fails when using cache_set with string

### ISSUE THREAD

**Issue by ferrouswheel** [ideegeo/Daemonise#16]
Ran into trouble because I tried to use `$d->cache_set` from the KyotoTycoon plugin with a plain string as the value. While the documentation says "complex data" it doesn't say anything about the requirements of the cache value being a reference and no warnings/errors were raised.

It'd be great if it either: threw an exception, logged a warning that the value wasn't the correct type, or supported storing a string.

I could use `$d->tycoon->set` but that feels too much like I'm relying on the internals of the plugin set/retrieve values from the cache.

**Comment by nupfel** [comment]
good point, it should be trivial to support non refs without the overhead of encoding, freezing, thawing and decoding necessary for refs.

**Comment by nupfel** [comment]
btw, currently cache_set() returns `true` on success and `false` otherwise. so it is possible to check and error handle.

**Comment by nupfel** [comment]
working on https://github.com/ideegeo/Daemonise/pull/18 for this

**Comment by nupfel** [comment]
tested and rolled out.

`cache_set()` can now handle scalars as well as complex data structures and transparently encodes/decodes them. this should make it easier to just store "stuff" in the cache without having to think about internals.

**Comment by ferrouswheel** [comment]
nice one!
