### ISSUE TITLE
Use cross-language serialisation format for cache

### ISSUE THREAD

**Issue by ferrouswheel** [ideegeo/Daemonise#19]
I was reminded of this when #16 was closed.

To interact with daemonise-backed services, some actions would be easier if they could read from the same cache. We currently thaw/freeze data, but implementing that in other languages will be a pain. Something like http://msgpack.org/ would probably work well (perl implementation [here](http://perl.msgpack.org/) )

The more tricky part would be a migration strategy for existing data.

**Comment by nupfel** [comment]
I like this very much. Looks very easy to implement and we could migrate transparently by encoding always to `msgpack` and to decode try `msgpack` first, if that fails fall back to `storable`.
