### ISSUE TITLE
msgpack vs json

### ISSUE THREAD

**Issue by norbu09** [ideegeo/Daemonise#24]
I know `msgpack` is a "universal" serialisation protocol but it is actually not that universal. When we looked for a layer that is compatible with Perl and elixir we went back to JSON as a serialisation protocol and wrote the following compatibility layer to round-trip elixir data structures to perl land and back: https://github.com/iwantmyname/venom

It might be good to re-consider msgpack and replace it with a simple JSON layer, compatible with more languages and more universal to hack it for round-tripping data structures that are not supported in one of the languages that reads keys from KT

**Comment by polymetis** [comment]
https://github.com/lexmag/msgpax

**Comment by norbu09** [comment]
We tried to round-trip Phoenix sessions through it when we wrote the JSON hack and it failed to import a valid Phoenix session. They may have done work on it since, not sure it is worth changing the session code though.

**Comment by robramsaynz** [comment]
From memory the main problem was that the none of the message formats handled atoms, and round-triping an atom gave you a string. This was causing us problems when we saved plug data so we wrote venom to get around the problem.

Venom is: pretty much straight json; extensible for new types in a predictable way; easy to ignore for languages that don't support any of the type; good at escaping malicious user input.

**Comment by dch** [comment]
On Thu, 16 Mar 2017, at 03:22, Rob Ramsay wrote:
> From memory the main problem was that the none of the message formats
> handled atoms, and round-triping an atom gave you a string. This was
> causing us problems when we saved plug data so we wrote venom to get
> around the problem.
> 
> Venom is: pretty much straight json; extensible for new types in a
> predictable way; easy to ignore for languages that don't support any of
> the type; good at escaping malicious user input.

And the best name. Very important!

**Comment by robramsaynz** [comment]
Ask anybody; iwantmyname has the best names. They all say; "your names are amazing".

**Comment by dch** [comment]
My son is amazing, he chooses the best names at iwantmyname. Even my friends the Russians use them -- Vladimir is a close friend of mine.

**Comment by dch** [comment]
I's time to make your name great again.

**Comment by nupfel** [comment]
msgpack has been the default in Daemonise for a while now, but falls back to using Storable as before. the iwantmyname session wasn't actually handled in Daemonise so this isn't relevant anymore.
But for future ideas it would be nice to have a switch in Daemonise that lets everyone choose which encoding they want and maybe a configurable fallback as well for migrations.
