### ISSUE TITLE
RabbitMQ plugin doesn't preserve the correlation_id message property

### ISSUE THREAD

**Issue by ferrouswheel** [ideegeo/Daemonise#7]
It is reasonably common practice when doing RPC over rabbitmq to use a `correlation_id` to match up response with requests.

Daemonise doesn't preserve the `correlation_id`, instead assuming every reply has it's own queue. It'd be nice if it would copy this property to the response message if it exists to allow interoperability with other messaging systems that expect this convention to be used.

From rabbitmq's own tutorial https://www.rabbitmq.com/tutorials/tutorial-six-python.html -

> In the method presented above we suggest creating a callback queue for every RPC request. That's pretty inefficient, but fortunately there is a better way - let's create a single callback queue per client.

**Comment by nupfel** [comment]
finally implemented in https://github.com/ideegeo/Daemonise/commit/f6d378e0366cea2b53c0287f36991f29f7294b20

**Comment by ferrouswheel** [comment]
:+1: Woot!
